# Generated by Django 4.2.3 on 2025-03-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="subscriptsion",
            new_name="subscription",
        ),
    ]
