# Generated by Django 4.2.3 on 2025-03-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_alter_feedback_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="locations",
            name="category",
            field=models.CharField(default="404", max_length=100),
        ),
    ]
