# Generated by Django 4.2.3 on 2025-03-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_locations_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
